[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "tiny-python-utils"
version = "0.1.0"
description = "Small, useful Python utilities"
requires-python = ">=3.9"
